options <- commandArgs(trailingOnly = TRUE)
neural_net_file <- as.character(options[1])
library("nnet")
load(neural_net_file)
prediction_class <- predict(neural_net, type="class")
prediction_prob <- predict(neural_net, type="raw")
cat("LEVELS\n")
cat(neural_net$lev)
cat("\nCLASSES\n")
cat(prediction_class[1:length(prediction_class)])
cat("\nPROBABILITIES\n")
cat(format(prediction_prob[1:length(prediction_prob)], , big.mark=",", scientific=FALSE))
cat("\n")
